services:
    mariadb:
        env_file: .env
        build: ./requirements/mariadb
        volumes:
            - DB:/var/lib/mysql/mysql
        networks:
            - networkapp
    wordPress:
        env_file: .env
        build: ./requirements/wordpress
        depends_on:
            - mariadb
        volumes:
            - wordPres:/var/www/html
        networks:
            - networkapp
    nginx:
        env_file: .env
        build: ./requirements/nginx
        depends_on:
            - wordPress
        volumes:
            -wordPres:/var/www/html
        networks:
            - networkapp



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/login/data/mariadb

networks:
    networkapp:
        driver: bridge

secrets:
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password
    wp_password:
        file: ../secrets/credentials
