services:
  mariadb:
    container_name: mariadb
    env_file: ../.env
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - networkapp
    restart: always
    secrets:
      - db_root_password
      - db_password

  wordpress:
    container_name: wordpress
    env_file: ../.env
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - networkapp
    restart: always
    secrets:
      - db_password
      - wp_password

  nginx:
    container_name: nginx
    env_file: ../.env
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - networkapp
    restart: always
    ports:
      - "443:443"
 
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/aferryat/data/wordpress"

  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/aferryat/data/mariadb"

networks:
  networkapp:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt

  db_root_password:
    file: ../secrets/db_root_password.txt

  wp_password:
    file: ../secrets/wp_password.txt
